# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://geeksai.com
date_format: "ordinal"
title: Sam Blog
subtitle: "If you can measure it, you can improve it"
description: "Sam的个人博客"
keywords: Sam, python, 前端, 区块链
timezone: Asia/Beijing
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Sam Ding
organization: ''
organization_url: ''
github_username: sam408130
location: Beijing, China
email: sam408130@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: sam408130/sam408130.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: sam408130
    repo: blog-comments
    oauth:
        client_id: 3a4264603bd9683c3fed
        client_secret: 120ed20f7912ae9327d45acc84f5851018f84ecc
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: sam408130
    repo: blog-comments
    clientID: 3a4264603bd9683c3fed
    clientSecret: 120ed20f7912ae9327d45acc84f5851018f84ecc
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-116921402-1
